
import { FC, PropsWithChildren } from "react"

import styles from'./MainLayout.module.css'
import Head from 'next/head'
import {NavBar} from '../NavBar'
export const MainLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
       <NavBar />
          <main className={styles.main}>
          {children}
          </main>
        </div>
      );
}

export default MainLayout
